name: flutter_clean_architecture
description: Example project using clean archtecture on flutter
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.4
  json_annotation: ^4.4.0
  flutter_mobx: ^2.0.5
  injectable: ^1.5.3
  http: ^0.13.4
  get_it: ^7.2.0
  mobx: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.6
  mobx_codegen: ^2.0.6
  build_runner: ^2.1.10
  mockito: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
